// Copyright (c) 2026 Thibaud Maneval - Techtical (https://www.techtical.fr)
// SPDX-License-Identifier: MIT

package fr.techtical.nextsh.shared.core.import

/**
 * Sanitization helpers for untrusted import data.
 *
 * Every importer treats parsed text as hostile: Termius / KeePassXC export files
 * may have been edited by hand, generated by a third-party tool, or crafted to
 * inject control characters / shell metacharacters into a hostname or username.
 *
 * Rules applied here (see [HostImportService] for where they gate the import):
 *  - hostname / username are trimmed; entries containing NUL, control chars, or
 *    line breaks are rejected (return null): they are never silently truncated.
 *  - port is clamped to 1..65535; an unparseable / out-of-range port falls back
 *    to [DEFAULT_SSH_PORT] (22) on parse, but [sanitizePortStrict] rejects an
 *    out-of-range explicit value so the caller can choose to skip.
 *  - label falls back to the (sanitized) hostname when blank.
 *
 * SECURITY: never log the values passed through here: they may sit next to
 * passwords in the source file, and a hostname is itself low-sensitivity but a
 * username often is not.
 */
internal object ImportSanitizer {

    const val DEFAULT_SSH_PORT: Int = 22
    private const val MIN_PORT = 1
    private const val MAX_PORT = 65535

    /** Max length we accept for a host/user/label field, defends against absurd inputs. */
    private const val MAX_FIELD_LEN = 4096

    /**
     * Trims [raw] and returns it only if it is a single clean line with no control
     * characters, NUL, or whitespace line breaks. Returns null for blank input or
     * any value that would be unsafe to persist / use as an SSH hostname or login.
     */
    fun sanitizeIdentifier(raw: String?): String? {
        if (raw == null) return null
        val trimmed = raw.trim()
        if (trimmed.isEmpty()) return null
        if (trimmed.length > MAX_FIELD_LEN) return null
        if (containsControlOrLineBreak(trimmed)) return null
        return trimmed
    }

    /**
     * Sanitizes a free-text label. Unlike [sanitizeIdentifier] this never returns
     * null: a control-char-laden or blank label degrades to [fallback] (typically
     * the sanitized hostname). Embedded line breaks / control chars are stripped
     * so the label is always a safe single-line display string.
     */
    fun sanitizeLabel(raw: String?, fallback: String): String {
        val cleaned = raw
            ?.filterNot { it.isControlOrLineBreak() }
            ?.trim()
            ?.take(MAX_FIELD_LEN)
        return if (cleaned.isNullOrEmpty()) fallback else cleaned
    }

    /**
     * Sanitizes an optional group / folder name. Returns null if blank or unsafe
     * (groups are optional metadata, a hostile value is dropped rather than kept).
     */
    fun sanitizeGroup(raw: String?): String? {
        val cleaned = sanitizeIdentifier(raw) ?: return null
        // A bare "/" or root-only path carries no grouping information.
        return cleaned.trim('/').ifEmpty { null }
    }

    /**
     * Parses and clamps a port. A null/blank/non-numeric value yields
     * [DEFAULT_SSH_PORT]; a numeric value outside 1..65535 is clamped into range.
     * Use this on the lenient parse path where we always want a usable port.
     */
    fun sanitizePortLenient(raw: String?): Int {
        val parsed = raw?.trim()?.toIntOrNull() ?: return DEFAULT_SSH_PORT
        return parsed.coerceIn(MIN_PORT, MAX_PORT)
    }

    /**
     * Strict variant: returns null when [raw] is present but out of the legal
     * 1..65535 range (e.g. "99999"), letting the caller skip the malformed entry
     * rather than silently coercing. A null/blank input still yields the default.
     */
    fun sanitizePortStrict(raw: String?): Int? {
        val trimmed = raw?.trim()
        if (trimmed.isNullOrEmpty()) return DEFAULT_SSH_PORT
        val parsed = trimmed.toIntOrNull() ?: return null
        return if (parsed in MIN_PORT..MAX_PORT) parsed else null
    }

    /** Same clamping as [sanitizePortLenient] but for an already-parsed Int. */
    fun clampPort(port: Int): Int = port.coerceIn(MIN_PORT, MAX_PORT)

    private fun containsControlOrLineBreak(value: String): Boolean =
        value.any { it.isControlOrLineBreak() }

    private fun Char.isControlOrLineBreak(): Boolean {
        // NUL, all C0 controls (incl. CR/LF/TAB), DEL, and C1 controls.
        return this.code == 0 ||
            this.code in 0x01..0x1F ||
            this.code == 0x7F ||
            this.code in 0x80..0x9F
    }
}
