import java.net.URI
import java.security.MessageDigest
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import java.time.LocalDate

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose.compiler)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.sqldelight)
}

// ─────────────────────────────────────────────────────────────────────────
// Source unique de version Desktop. Bump ICI uniquement à chaque release.
// Câblée plus bas vers packageVersion / exePackageVersion / msiPackageVersion,
// vers les noms d'artefacts (MSI / EXE / ZIP portable) ET vers la version
// in-app exposée par `DesktopBuildInfo` (généré par `generateDesktopBuildInfo`).
//
// ⚠️ La version interne du MSI DOIT croître strictement d'une release à
// l'autre. jpackage dérive le ProductCode de façon déterministe depuis
// l'upgradeUuid + cette version ; si elle ne change pas, Windows Installer voit
// le même produit et répond « déjà installé » au lieu de mettre à jour.
// L'upgradeUuid (voir bloc `windows {}`) reste lui STABLE entre les releases.
// ─────────────────────────────────────────────────────────────────────────
val desktopVersion = "1.0.0"

// X11 WM_CLASS the running Compose/AWT window reports. AWT derives it from
// the main class FQN (fr.techtical.nextsh.desktop.MainKt → dots become
// dashes), confirmed via `xprop WM_CLASS`. The Linux desktop entries
// (AppImage + .deb) MUST carry this exact value as `StartupWMClass=` so the
// taskbar/dock can map the running window to its icon. Without it the window
// shows a generic icon while the app-menu entry shows the right one. If the
// main class is ever renamed or moved, update this to match `xprop WM_CLASS`.
val linuxWmClass = "fr-techtical-nextsh-desktop-MainKt"
// Site du produit : ARP Windows (--about-url), Homepage du .deb, AppStream Linux.
val nextshHomepage = "https://www.techtical.fr"

// Génère `DesktopBuildInfo.kt` (version runtime affichée dans la status bar)
// depuis `desktopVersion`. Remplace l'ancien fichier saisi à la main : plus
// aucune double-saisie, donc aucune dérive possible entre la version packagée
// et la version affichée. Zéro dépendance (pas de plugin buildconfig).
val generateDesktopBuildInfo by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/desktopBuildInfo/kotlin")
    val versionValue = desktopVersion
    inputs.property("version", versionValue)
    outputs.dir(outDir)
    doLast {
        val pkgDir = outDir.get().dir("fr/techtical/nextsh/desktop").asFile
        pkgDir.mkdirs()
        // ASCII-only comments on purpose: this is generated code and we don't
        // want to depend on the reader's charset. The value itself is plain.
        File(pkgDir, "DesktopBuildInfo.kt").writeText(
            """
            |// Copyright (c) 2026 Thibaud Maneval - Techtical (https://www.techtical.fr)
            |// SPDX-License-Identifier: MIT
            |//
            |// GENERATED FILE - DO NOT EDIT BY HAND.
            |// Single source of truth: desktop/build.gradle.kts -> `desktopVersion`.
            |// Regenerated by the Gradle task `generateDesktopBuildInfo`.
            |package fr.techtical.nextsh.desktop
            |
            |object DesktopBuildInfo {
            |    const val VERSION = "$versionValue"
            |}
            |
            """.trimMargin(),
            Charsets.UTF_8,
        )
    }
}

kotlin {
    jvm("desktop") {
        compilations.all {
            kotlinOptions.jvmTarget = "17"
            // java.smartcardio is an optional JDK module; make it visible to the Kotlin compiler
            // so we can use javax.smartcardio.* directly without reflection.
            kotlinOptions.freeCompilerArgs += listOf("-Xadd-modules=java.smartcardio")
        }
    }
    sourceSets {
        val desktopMain by getting {
            // Source générée : DesktopBuildInfo.kt (version runtime). Le
            // provider crée automatiquement la dépendance de compilation.
            kotlin.srcDir(generateDesktopBuildInfo)
            dependencies {
                implementation(project(":shared"))
                implementation(compose.desktop.currentOs)
                implementation(compose.material3)
                implementation(compose.materialIconsExtended)
                implementation(compose.components.resources)
                implementation(libs.compose.icons.lucide)
                implementation(libs.sqldelight.runtime)
                implementation(libs.sqldelight.sqlite.driver)
                implementation(libs.sqldelight.coroutines.ext)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.bouncycastle.bcprov)
                implementation(libs.bouncycastle.bcpkix)
                implementation(libs.sshj)
                implementation(libs.i2p.eddsa)  // transitive via sshj; declared explicit so we can reference `net.i2p.crypto.eddsa.*` at compile time for the Ed25519 provider
                // jediterm-core only: the parser/model layer used by the
                // Compose-native terminal renderer (sessions/compose/*).
                // jediterm-ui (Swing TerminalPanel/JediTermWidget) was
                // dropped when the Swing renderer was removed in favour of
                // the Compose Canvas renderer as the sole implementation.
                implementation(libs.jediterm.core)
                implementation(libs.ktor.server.core)
                implementation(libs.ktor.server.cio)
                implementation(libs.ktor.server.netty)
                implementation(libs.ktor.server.content.negotiation)
                implementation(libs.ktor.serialization.json)
                implementation(libs.zxing.core)
                implementation(libs.zxing.javase)
                // YubiKit Desktop, FIDO2 via PC/SC (USB + NFC reader), Mode A: import + sign
                implementation(libs.yubikit.desktop)
                implementation(libs.yubikit.core.desktop)
                implementation(libs.yubikit.fido.desktop)
                // JNA: Windows WebAuthn API native (webauthn.dll) bindings
                implementation(libs.jna)
                implementation(libs.jna.platform)
                implementation(libs.kcef)
                runtimeOnly(libs.slf4j.nop)
            }
        }
        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.test)
                implementation(libs.ktor.server.test.host)
                implementation(libs.mockk)
            }
        }
    }
}

compose.desktop {
    application {
        mainClass = "fr.techtical.nextsh.desktop.MainKt"

        // JVM-native splash: the launcher decodes this PNG and shows it
        // BEFORE `main()` is invoked, so the user sees the brand mark
        // within ~100 ms of double-clicking the installed .exe. Closed
        // from Main.kt via `SplashScreen.getSplashScreen()?.close()` in
        // the post-show LaunchedEffect, once the real Compose window is
        // themed and visible.
        //
        // Why not draw the splash from a `JWindow` inside main()? An
        // earlier attempt cost 6.3 s on the first run after MSI install
        // because the Toolkit + Swing + ImageIO class graph paged in
        // from disk synchronously. The JVM splash sidesteps that
        // entirely: it runs in the native launcher, before the JVM
        // proper starts class-loading.
        //
        // Path: the launcher's libjli initialises the splash BEFORE the
        // application classpath is constructed, so a path inside our
        // jars (`icons/nextsh_256.png`) cannot be resolved: libjli
        // returns silently and `SplashScreen.getSplashScreen()` is null.
        // We instead drop a copy of the PNG into `appResourcesRootDir`
        // below. Compose Desktop / jpackage copies that directory's
        // contents to `$APPDIR\resources\` at install time, and
        // jpackage's launcher expands `$APPDIR` in --java-options
        // before invoking libjli. So at launch the flag is a real
        // absolute filesystem path the splash code can decode.
        //
        // In dev (`:desktop:run`), `$APPDIR` isn't substituted,
        // the JVM sees the literal `$APPDIR\...` path, fails to
        // locate the file, and silently skips the splash. That's
        // acceptable: dev iteration doesn't need a splash, and the
        // close-call in main() is null-safe.
        // Forward slashes: jpackage writes the flag verbatim into
        // NextSH.cfg, and the properties-file parser there interprets
        // backslash sequences as escapes (`\r`, `\s`, `\n` collapse).
        // `/` is accepted by Windows path resolution and avoids the
        // escape pitfall entirely.
        jvmArgs += listOf("-splash:\$APPDIR/resources/splash.png")

        // AppCDS auto-archive was tried (commits 6daf73b/0f87dbe) but
        // never produced an `app.jsa` on disk: the JVM silently refused
        // to dump under our stack (jlink minimal JRE + Compose/Skiko
        // bootclasspath append). Removed to avoid carrying dead config;
        // can be revisited later with `-Xlog:cds` to see why the dump
        // failed, but the JVM `-splash:` alone already covers the UX
        // concern (visible <300 ms after click, hides the 2 s
        // intrinsic Compose/Skiko cold init behind the brand mark).

        nativeDistributions {
            // Ships an extra resources directory copied to
            // `$APPDIR\resources\` inside the installed app. Currently
            // hosts `splash.png` consumed by the `-splash:` JVM flag
            // above. Keep dedicated to launcher-time resources: files
            // here are NOT in the JVM classpath, only on the filesystem.
            appResourcesRootDir.set(project.file("src/desktopMain/appResources"))
            targetFormats(
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Msi,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Exe,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.Deb,
                org.jetbrains.compose.desktop.application.dsl.TargetFormat.AppImage,
            )
            packageName = "NextSH"
            packageVersion = desktopVersion
            description = "Native SSH client with encrypted vault"
            copyright = "© 2026 Techtical"
            vendor = "Techtical"

            // jlink module set required at runtime. Compose Desktop uses
            // jlink to bundle a minimal JRE inside MSI/EXE/AppImage/Deb;
            // any module referenced by the app or its dependencies must
            // be listed here, otherwise the packaged JRE fails to launch
            // with "Failed to launch JVM" / "JNI error" / "Java Exception".
            //
            // This list was determined empirically from our deps:
            //  - java.base, java.desktop                  always required (Swing/AWT)
            //  - java.instrument, java.logging            Compose + Timber + Slf4j
            //  - java.management                          Ktor / Netty internal
            //  - java.naming                              BouncyCastle JCE / JNDI
            //  - java.net.http                            Ktor HTTP client
            //  - java.prefs                               DesktopSettingsStore
            //  - java.scripting                           BouncyCastle / JediTerm
            //  - java.security.jgss, java.security.sasl   SSH/SASL auth
            //  - java.smartcardio                         YubiKit PC/SC (USB+NFC)
            //  - java.sql, java.sql.rowset                SQLDelight JdbcSqliteDriver
            //  - java.xml                                 Compose Resources / XML
            //  - jdk.crypto.ec, jdk.crypto.cryptoki       SSHJ EC + PKCS#11
            //  - jdk.unsupported                          sun.misc.Unsafe (Netty,
            //                                             kotlinx.coroutines, etc.)
            //  - jdk.unsupported.desktop                  some Compose internals
            //  - jdk.zipfs                                NIO zip filesystem
            //
            // To regenerate this list precisely, run:
            //   ./gradlew :desktop:suggestRuntimeModules
            // (requires a full JDK with jpackage, Android Studio's JBR
            //  does not include it).
            modules(
                "java.base",
                "java.desktop",
                "java.instrument",
                "java.logging",
                "java.management",
                "java.naming",
                "java.net.http",
                "java.prefs",
                "java.scripting",
                "java.security.jgss",
                "java.security.sasl",
                "java.smartcardio",
                "java.sql",
                "java.sql.rowset",
                "java.xml",
                "jdk.crypto.cryptoki",
                "jdk.crypto.ec",
                "jdk.unsupported",
                "jdk.unsupported.desktop",
                "jdk.zipfs",
            )

            windows {
                iconFile.set(file("src/desktopMain/resources/icons/nextsh.ico"))
                menuGroup = "NextSH"
                // Stable upgrade UUID. DO NOT MODIFY between releases.
                // Changing this would make new installers fail to upgrade
                // existing installations and create duplicate Programs &
                // Features entries. Generated once, before the first public release.
                upgradeUuid = "BE25B998-2635-49FB-964A-0F393C2065A3"
                shortcut = true
                dirChooser = true
                perUserInstall = true
                exePackageVersion = desktopVersion
                msiPackageVersion = desktopVersion
            }

            linux {
                iconFile.set(file("src/desktopMain/resources/icons/nextsh_256.png"))
                packageName = "nextsh"
                debMaintainer = "thibaud.maneval@techtical.fr"
                menuGroup = "Network"
                appCategory = "Network"
                appRelease = "1"
            }
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Windows MSI/EXE: jpackage invoked OURSELVES (not via Compose Desktop's
// own `packageMsi`/`packageExe`), so a custom `--resource-dir` actually
// reaches jpackage instead of being silently discarded.
//
// CORRECTION (this comment used to claim Compose Desktop exposes no
// jpackage `--resource-dir` hook at all. That was wrong; jpackage HAS
// always had one). Compose Desktop's own packageMsi/packageExe tasks DO
// pass `--resource-dir` to jpackage, confirmed straight from a real
// build's `desktop/build/compose/tmp/packageMsi.args.txt`, but it points
// at `build/compose/tmp/resources`, a directory the plugin's task action
// CLEARS (`clearDirs`) before jpackage runs, and appends its OWN
// `--resource-dir` value after any `freeArgs` we could inject, so there is
// no way to land a custom `main.wxs` there through the DSL. Calling
// jpackage directly, against the already-built app-image from
// `createDistributable`, is what actually lets us point `--resource-dir`
// at our own `installer/windows/jpackage/` (custom `main.wxs` +
// NextSH-branded banner/dialog bitmaps, see that file's header comment
// for the WiX-side details, verified by decompiling the exact
// WixUtilExtension.dll / WixUIExtension.dll this project downloads).
//
// Flags below mirror Compose's own invocation 1:1 (see
// `packageMsi.args.txt` / `packageExe.args.txt`, both captured from a real
// build) minus the app-image-CONSTRUCTION-only flags (--input, --main-jar,
// --main-class, --runtime-image, --java-options): jpackage ignores those
// once `--app-image` is given, because we are re-packaging the app-image
// `createDistributable` already built, not building one from scratch.
//
// WiX toolset: reused from the SAME pinned download Compose Desktop's own
// plugin uses (`downloadWix` / `unzipWix`, registered on the root project,
// see `org.jetbrains.compose.desktop.application.internal.WixToolsetKt`,
// same `wix3112rtm/wix311-binaries.zip` release URL). Depending on them via
// `tasks.matching { }` rather than `tasks.named(...)` is deliberate: those
// tasks are created lazily by the plugin only once some Windows jpackage
// task is realized, and `named(...)` would throw immediately if that
// hasn't happened yet by the time this script evaluates; `matching { }` is
// resolved later, at task-graph time, once `createDistributable` (also an
// `AbstractJPackageTask`, required below) has triggered that lazy setup.
// ─────────────────────────────────────────────────────────────────────────

/** Absolute path to the custom jpackage Windows resource-dir (main.wxs + brand bitmaps). */
val nextshWindowsResourceDir = project.file("installer/windows/jpackage")

/**
 * Runs jpackage against the app-image `createDistributable` already built,
 * producing [type] ("msi" or "exe") into `compose/binaries/main/<destName>/`,
 * the SAME directories Compose's own packageMsi/packageExe used, so
 * `renameWindowsArtifacts` below needs no changes to find the output.
 */
fun packageWindowsWithResources(type: String, destName: String) {
    val appImageDir = layout.buildDirectory.dir("compose/binaries/main/app").get().asFile
        .listFiles()?.firstOrNull { it.isDirectory }
        ?: error("packageWindowsWithResources($type): no app-image found under " +
            "build/compose/binaries/main/app (did :desktop:createDistributable run?)")
    val destDir = layout.buildDirectory.dir("compose/binaries/main/$destName").get().asFile
    // Wipe first: jpackage refuses to overwrite an existing installer and
    // simply leaves the old one in place, so without this a failed or
    // skipped run would silently ship the PREVIOUS build, same version
    // number, stale bits. `renameWindowsArtifacts` then picks up an exact
    // filename that is guaranteed to come from this run.
    destDir.deleteRecursively()
    destDir.mkdirs()

    val wixBinDir = rootProject.layout.buildDirectory.dir("wix311").get().asFile
    val inheritedPath = System.getenv("PATH").orEmpty()

    exec {
        environment("NEXTSH_WIX_BRANDING_DIR", nextshWindowsResourceDir.absolutePath)
        environment("PATH", "${wixBinDir.absolutePath}${File.pathSeparator}$inheritedPath")
        commandLine(
            "jpackage",
            "--type", type,
            "--app-image", appImageDir.absolutePath,
            "--dest", destDir.absolutePath,
            "--resource-dir", nextshWindowsResourceDir.absolutePath,
            "--name", "NextSH",
            "--app-version", desktopVersion,
            "--vendor", "Techtical",
            "--copyright", "© 2026 Techtical",
            "--description", "Native SSH client with encrypted vault",
            "--about-url", nextshHomepage,
            "--icon", project.file("src/desktopMain/resources/icons/nextsh.ico").absolutePath,
            "--win-dir-chooser",
            "--win-per-user-install",
            "--win-shortcut",
            "--win-menu",
            "--win-menu-group", "NextSH",
            "--win-upgrade-uuid", "BE25B998-2635-49FB-964A-0F393C2065A3",
        )
    }
}

tasks.register("packageMsiWithResources") {
    dependsOn("createDistributable")
    dependsOn(rootProject.tasks.matching { it.name == "downloadWix" || it.name == "unzipWix" })
    doLast {
        val osName = System.getProperty("os.name", "").lowercase()
        if (!osName.contains("windows")) {
            logger.warn("packageMsiWithResources: not on Windows ($osName), skipping.")
            return@doLast
        }
        packageWindowsWithResources("msi", "msi")
        println("✓ MSI built with custom resource-dir (branding + CloseApplication).")
    }
}

tasks.register("packageExeWithResources") {
    dependsOn("createDistributable")
    dependsOn(rootProject.tasks.matching { it.name == "downloadWix" || it.name == "unzipWix" })
    doLast {
        val osName = System.getProperty("os.name", "").lowercase()
        if (!osName.contains("windows")) {
            logger.warn("packageExeWithResources: not on Windows ($osName), skipping.")
            return@doLast
        }
        packageWindowsWithResources("exe", "exe")
        println("✓ EXE built with custom resource-dir (branding + CloseApplication).")
    }
}

// Windows MSI/EXE artifact collection. Compose Desktop names the outputs
// `NextSH-<version>.msi` / `NextSH-<version>.exe` inside
// `build/compose/binaries/main/{msi,exe}/`. We COPY (not rename) them to
// `build/release-artifacts/` with the canonical names so:
//   1. The original outputs stay where Gradle's incremental machinery
//      tracks them, re-running `packageMsi` / `packageExe` can cleanly
//      recreate their directories (renaming in-place broke that: Gradle
//      tried to delete `exe/` next run and failed because the renamed
//      `*-setup.exe` was unrecognised by its cleanup tracker).
//   2. The release-artifacts directory has the canonical filenames the
//      GitHub Release expects (`NextSH-<version>-setup.exe` for the
//      installer, to distinguish it from the portable ZIP).
//
// The version comes from `desktopVersion` (single source of truth), never
// hardcode it here, or the filename drifts from the MSI's internal version.
tasks.register("renameWindowsArtifacts") {
    dependsOn("packageMsiWithResources", "packageExeWithResources")
    doLast {
        val releaseDir = layout.buildDirectory.dir("release-artifacts").get().asFile
        releaseDir.mkdirs()

        // Exact filenames, not "the first *.msi in the directory": jpackage
        // names its output `NextSH-<app-version>.<type>`, and matching by
        // extension alone would happily pick up a leftover from an earlier
        // version. Missing file => hard failure, because the previous
        // `?.copyTo(...)` silently produced NO release artifact at all when
        // the packaging step had been skipped (non-Windows host) or failed.
        val msiSource = File(
            layout.buildDirectory.dir("compose/binaries/main/msi").get().asFile,
            "NextSH-$desktopVersion.msi",
        )
        if (!msiSource.isFile) {
            error(
                "renameWindowsArtifacts: expected MSI not found at ${msiSource.absolutePath}. " +
                    "Run :desktop:packageMsiWithResources on Windows first.",
            )
        }
        msiSource.copyTo(File(releaseDir, "NextSH-$desktopVersion.msi"), overwrite = true)

        val exeSource = File(
            layout.buildDirectory.dir("compose/binaries/main/exe").get().asFile,
            "NextSH-$desktopVersion.exe",
        )
        if (!exeSource.isFile) {
            error(
                "renameWindowsArtifacts: expected EXE not found at ${exeSource.absolutePath}. " +
                    "Run :desktop:packageExeWithResources on Windows first.",
            )
        }
        exeSource.copyTo(File(releaseDir, "NextSH-$desktopVersion-setup.exe"), overwrite = true)

        println("✓ Windows installers ready in $releaseDir")
    }
}

// Portable Windows ZIP: distinct from MSI/EXE installers. Builds a
// self-contained directory with: (1) the uber JAR, (2) a minimal jlink
// JRE, (3) a launch .bat, then zips the lot.
//
// Rationale: users who can't install MSI/EXE (locked-down corp machines,
// USB-stick scenarios) need a no-install option. Java is NOT assumed to
// be present on the host, so the JRE must travel inside the ZIP.
tasks.register("packagePortableWindows") {
    dependsOn("packageUberJarForCurrentOS")
    doLast {
        val portableDir = layout.buildDirectory.dir("portable").get().asFile
        portableDir.deleteRecursively()
        portableDir.mkdirs()

        // 1. Copy fat JAR
        val uberJar = layout.buildDirectory.dir("compose/jars").get().asFile
            .listFiles()
            ?.firstOrNull { it.extension == "jar" }
            ?: error("Uber JAR not found in build/compose/jars")
        uberJar.copyTo(File(portableDir, "NextSH.jar"), overwrite = true)

        // 2. jlink minimal JRE: same module set as nativeDistributions.
        val jreDir = File(portableDir, "jre")
        exec {
            // Keep this list IN SYNC with the `modules(...)` block in
            // nativeDistributions above. Mismatch → MSI/EXE/portable
            // launch fails with "Failed to launch JVM" or "JNI error".
            commandLine(
                "jlink",
                "--add-modules",
                listOf(
                    "java.base", "java.desktop", "java.instrument", "java.logging",
                    "java.management", "java.naming", "java.net.http", "java.prefs",
                    "java.scripting", "java.security.jgss", "java.security.sasl",
                    "java.smartcardio", "java.sql", "java.sql.rowset", "java.xml",
                    "jdk.crypto.cryptoki", "jdk.crypto.ec", "jdk.unsupported",
                    "jdk.unsupported.desktop", "jdk.zipfs",
                ).joinToString(","),
                "--strip-debug",
                "--no-man-pages",
                "--no-header-files",
                // `--compress=2` was removed in JDK 21+. Modern syntax is
                // `--compress=zip-N` (N=0–9). zip-6 = sane default that
                // gives ~30 % smaller JRE without significant unzip cost.
                "--compress=zip-6",
                "--output", jreDir.absolutePath,
            )
        }

        // 3. Launch script
        File(portableDir, "NextSH-portable.bat").writeText(
            buildString {
                appendLine("@echo off")
                appendLine("set SCRIPT_DIR=%~dp0")
                appendLine("\"%SCRIPT_DIR%jre\\bin\\javaw.exe\" -jar \"%SCRIPT_DIR%NextSH.jar\"")
            }
        )

        // 4. Zip: pure java.util.zip, no Ant / Gradle Zip task. The
        // Kotlin DSL handle on `ant.zip(...)` is awkward (would need
        // `ant.withGroovyBuilder { "zip"(...) }`) and a dedicated Zip
        // task wired via `dependsOn` would split this single doLast
        // block. Self-contained byte-streaming is the simplest path
        // and produces a standard deflate zip readable by every
        // unzipper. Output lands in `release-artifacts/` next to the
        // MSI / EXE so all three Windows artifacts sit together.
        val releaseDir = layout.buildDirectory.dir("release-artifacts").get().asFile
        releaseDir.mkdirs()
        val zipFile = File(releaseDir, "NextSH-$desktopVersion-portable.zip")
        if (zipFile.exists()) zipFile.delete()
        ZipOutputStream(zipFile.outputStream().buffered()).use { zos ->
            portableDir.walkTopDown()
                .filter { it.isFile }
                .forEach { file ->
                    val relativePath = portableDir.toPath()
                        .relativize(file.toPath())
                        .toString()
                        .replace('\\', '/')
                    zos.putNextEntry(ZipEntry(relativePath))
                    file.inputStream().buffered().use { it.copyTo(zos) }
                    zos.closeEntry()
                }
        }
        println("✓ Portable ZIP: ${zipFile.absolutePath} (${zipFile.length() / (1024 * 1024)} MB)")
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Real `.AppImage` single-file packaging (Linux only).
//
// IMPORTANT distinction: Compose Desktop's `TargetFormat.AppImage` /
// `packageAppImage` does NOT produce a `.AppImage` file. It produces a
// jpackage "app-image": an unpacked, runnable *directory* under
// `build/compose/binaries/main/app/<name>/`. The name collision with the
// Linux AppImage format is unfortunate but real.
//
// This task takes that directory and wraps it into a genuine single-file
// `.AppImage` distributable, the artifact the release process actually
// ships (see docs/RELEASE_PROCESS.md). The steps:
//   1. Build an AppDir: copy the jpackage app-image, add the freedesktop
//      bits AppImage requires (AppRun launcher, .desktop entry, icon).
//   2. Fetch a PINNED, checksum-verified `appimagetool` (AppImageKit 12).
//      It is self-contained (bundles mksquashfs), no system packages
//      beyond a working filesystem are needed to BUILD the AppImage.
//   3. Run it via APPIMAGE_EXTRACT_AND_RUN=1 so building needs no FUSE.
//
// Note: the RESULTING `.AppImage` still needs FUSE (libfuse2) to run on the
// end user's machine, or `./NextSH-*.AppImage --appimage-extract-and-run`.
//
// Linux-only: skips with a warning elsewhere (jpackage cannot cross-build
// the app-image for Linux from Windows/macOS anyway).
// ─────────────────────────────────────────────────────────────────────────
// Linux desktop metadata, shared by the .deb and the AppImage.
//
// jpackage writes a .desktop entry whose Icon= is an absolute /opt path and
// ships no AppStream metainfo, so software centers (GNOME Software, KDE
// Discover) show the package without logo, developer, licence or website.
// Both Linux tasks add the standard files: the themed icon under
// usr/share/icons/hicolor and the metainfo under usr/share/metainfo, from
// the template in desktop/installer/linux/ (next to the Windows resources).
// ─────────────────────────────────────────────────────────────────────────
val linuxAppStreamId = "fr.techtical.nextsh"
val linuxIconName = "nextsh"

/** The metainfo template with the desktop entry id, version and build date filled in. */
fun linuxMetainfo(desktopId: String): String =
    project.file("installer/linux/$linuxAppStreamId.metainfo.xml").readText(Charsets.UTF_8)
        .replace("@DESKTOP_ID@", desktopId)
        .replace("@VERSION@", desktopVersion)
        .replace("@DATE@", LocalDate.now().toString())
        .replace("\r\n", "\n")

/**
 * Drops the themed icon and the metainfo into an FHS tree. [root] is the
 * package data root (extracted .deb) or the AppDir; [metainfoFileName]
 * differs because appimagetool looks for `<desktop-id>.appdata.xml` while
 * the AppStream convention for packages is `<component-id>.metainfo.xml`.
 */
fun installLinuxMetadata(root: File, desktopId: String, metainfoFileName: String) {
    val icon = File(root, "usr/share/icons/hicolor/256x256/apps/$linuxIconName.png")
    icon.parentFile.mkdirs()
    project.file("src/desktopMain/resources/icons/nextsh_256.png").copyTo(icon, overwrite = true)
    val metainfo = File(root, "usr/share/metainfo/$metainfoFileName")
    metainfo.parentFile.mkdirs()
    metainfo.writeText(linuxMetainfo(desktopId), Charsets.UTF_8)
    validateLinuxMetainfo(metainfo)
}

/**
 * Validates a metainfo file with the system appstreamcli (package
 * `appstream`) when it is installed, and only warns when it is not. Errors
 * fail the build, warnings do not. Done here, with a clean environment,
 * rather than left to appimagetool: see packageRealAppImage.
 */
fun validateLinuxMetainfo(metainfo: File) {
    val cli = listOf("/usr/bin/appstreamcli", "/usr/local/bin/appstreamcli")
        .map { File(it) }
        .firstOrNull { it.canExecute() }
    if (cli == null) {
        logger.warn("${metainfo.name}: appstreamcli not installed, AppStream metainfo not validated (sudo apt install appstream)")
        return
    }
    exec { commandLine(cli.absolutePath, "validate", "--no-net", metainfo.absolutePath) }
    logger.lifecycle("${metainfo.name}: validated by appstreamcli")
}

// ─────────────────────────────────────────────────────────────────────────
tasks.register("packageRealAppImage") {
    dependsOn("packageAppImage")
    doLast {
        val osName = System.getProperty("os.name", "").lowercase()
        if (!osName.contains("linux")) {
            logger.warn("packageRealAppImage: not on Linux ($osName), skipping. " +
                "Build this on Ubuntu 22.04+ or WSL2.")
            return@doLast
        }

        // Map the JVM arch name to the AppImage arch token + its pinned
        // appimagetool checksum. Pins are AppImageKit release 12 (the last
        // tagged release that ships binaries; tag 13 has none). Verified
        // SHA-256 of the upstream release assets.
        data class ToolPin(val arch: String, val sha256: String)
        val pin = when (val a = System.getProperty("os.arch", "").lowercase()) {
            "amd64", "x86_64" -> ToolPin(
                "x86_64",
                "d918b4df547b388ef253f3c9e7f6529ca81a885395c31f619d9aaf7030499a13",
            )
            "aarch64", "arm64" -> ToolPin(
                "aarch64",
                "c9d058310a4e04b9fbbd81340fff2b5fb44943a630b31881e321719f271bd41a",
            )
            else -> error("packageRealAppImage: unsupported arch '$a' (need amd64/x86_64 or aarch64)")
        }

        // 1. Locate the jpackage app-image directory produced by packageAppImage.
        val appDirParent = layout.buildDirectory.dir("compose/binaries/main/app").get().asFile
        val jpackageImage = appDirParent.listFiles()?.firstOrNull { it.isDirectory }
            ?: error("packageRealAppImage: no app-image found under $appDirParent " +
                "(did :desktop:packageAppImage run?)")

        // 2. Assemble a fresh AppDir.
        val appDir = layout.buildDirectory.dir("appimage/AppDir").get().asFile
        appDir.deleteRecursively()
        appDir.mkdirs()
        // Use `cp -a` (this task is Linux-only) to PRESERVE the executable bit
        // on the jpackage launcher and bundled-JRE binaries. Kotlin's
        // File.copyRecursively copies content only: the launcher would land
        // as 0644 and the AppImage would die at startup with
        // "exec: .../bin/<name>: Permission denied".
        exec { commandLine("cp", "-aT", jpackageImage.absolutePath, appDir.absolutePath) }

        // Launcher binary lives at bin/<packageName>; resolve it dynamically.
        val launcher = File(appDir, "bin").listFiles()?.firstOrNull { it.isFile && it.canExecute() }
            ?: File(appDir, "bin").listFiles()?.firstOrNull { it.isFile }
            ?: error("packageRealAppImage: no launcher binary under $appDir/bin")
        launcher.setExecutable(true, false)  // belt-and-suspenders if cp ever changes
        val launcherName = launcher.name

        // AppRun: the AppImage entry point. Resolves its own location so the
        // bundled JRE + jars are found regardless of mount path.
        // NOTE: this build script is committed with CRLF line endings, so the
        // triple-quoted literals below carry \r\n. A shell script with a
        // `#!/bin/sh\r` shebang fails on Linux with "bad interpreter", so we
        // force LF on every generated text file. (.desktop is also LF-only.)
        val appRun = File(appDir, "AppRun")
        appRun.writeText(
            """
            |#!/bin/sh
            |HERE="${'$'}(dirname "${'$'}(readlink -f "${'$'}0")")"
            |exec "${'$'}HERE/bin/$launcherName" "${'$'}@"
            |
            """.trimMargin().replace("\r\n", "\n"),
            Charsets.UTF_8,
        )
        appRun.setExecutable(true, false)

        // Top-level .desktop entry (appimagetool requires exactly one). Named
        // after the AppStream id so appimagetool finds the matching
        // usr/share/metainfo/<id>.appdata.xml and validates the two together.
        val appImageDesktopId = "$linuxAppStreamId.desktop"
        val desktopEntry = File(appDir, appImageDesktopId)
        desktopEntry.writeText(
            """
            |[Desktop Entry]
            |Type=Application
            |Name=NextSH
            |Comment=Native SSH client with encrypted vault
            |Exec=$launcherName
            |Icon=$linuxIconName
            |Categories=Network;
            |Terminal=false
            |StartupWMClass=$linuxWmClass
            |
            """.trimMargin().replace("\r\n", "\n"),
            Charsets.UTF_8,
        )
        // Same entry under usr/share/applications for the desktop-integration
        // tools that read the FHS location.
        File(appDir, "usr/share/applications/$appImageDesktopId").apply {
            parentFile.mkdirs()
            desktopEntry.copyTo(this, overwrite = true)
        }

        // Top-level icon + .DirIcon (both expected by the AppImage spec), then
        // the themed icon and the AppStream metainfo.
        val srcIcon = project.file("src/desktopMain/resources/icons/nextsh_256.png")
        srcIcon.copyTo(File(appDir, "$linuxIconName.png"), overwrite = true)
        srcIcon.copyTo(File(appDir, ".DirIcon"), overwrite = true)
        installLinuxMetadata(appDir, appImageDesktopId, "$linuxAppStreamId.appdata.xml")

        // 3. Obtain appimagetool: prefer an operator-supplied binary
        // (APPIMAGETOOL env), else download the pinned release and verify
        // its SHA-256 before trusting it.
        val toolsDir = layout.buildDirectory.dir("tools").get().asFile.apply { mkdirs() }
        val envTool = System.getenv("APPIMAGETOOL")?.let { File(it) }?.takeIf { it.isFile }
        val tool = envTool ?: run {
            val cached = File(toolsDir, "appimagetool-${pin.arch}.AppImage")
            if (!cached.isFile || sha256(cached) != pin.sha256) {
                val url = "https://github.com/AppImage/AppImageKit/releases/download/12/" +
                    "appimagetool-${pin.arch}.AppImage"
                logger.lifecycle("packageRealAppImage: downloading $url")
                URI(url).toURL().openStream().use { input ->
                    cached.outputStream().use { input.copyTo(it) }
                }
                val got = sha256(cached)
                if (got != pin.sha256) {
                    cached.delete()
                    error("packageRealAppImage: appimagetool checksum mismatch\n" +
                        "  expected ${pin.sha256}\n  got      $got")
                }
            }
            cached
        }
        tool.setExecutable(true, false)

        // 4. Run appimagetool. APPIMAGE_EXTRACT_AND_RUN avoids needing FUSE to
        // run the tool; ARCH is required by the AppImage runtime to stamp the
        // output. Output lands in release-artifacts/ next to the other
        // installers. --no-appstream: the metainfo was already validated by
        // the system appstreamcli (installLinuxMetadata). appimagetool 12
        // would spawn it too, but its bundled 2014 glib leaks into the child
        // through LD_LIBRARY_PATH and crashes it (libxmlb: undefined symbol
        // g_ascii_string_to_unsigned), failing the build for nothing.
        val releaseDir = layout.buildDirectory.dir("release-artifacts").get().asFile
            .apply { mkdirs() }
        val output = File(releaseDir, "NextSH-$desktopVersion-${pin.arch}.AppImage")
        if (output.exists()) output.delete()
        exec {
            commandLine(tool.absolutePath, "--no-appstream", appDir.absolutePath, output.absolutePath)
            environment("APPIMAGE_EXTRACT_AND_RUN", "1")
            environment("ARCH", pin.arch)
        }
        output.setExecutable(true, false)
        println("✓ AppImage: ${output.absolutePath} (${output.length() / (1024 * 1024)} MB)")
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Inject `StartupWMClass` into the .deb's desktop entry (Linux only).
//
// jpackage's generated desktop entry (shipped under /opt/<pkg>/lib/ and
// registered at install time via xdg-desktop-menu in postinst) carries no
// `StartupWMClass`, so the Linux taskbar/dock cannot map the running window
// (WM_CLASS `fr-techtical-nextsh-desktop-MainKt`, derived by AWT from the
// main class) back to this entry: the running app shows a generic icon even
// though the app-menu shows the right one.
//
// CORRECTION (this comment used to claim Compose Desktop exposes no
// jpackage `--resource-dir` hook at all. Wrong, see the identical
// correction above `packageMsiWithResources`: jpackage itself has always
// had one, Compose's plugin task just clears/overrides it). jpackage's own
// Linux resource-dir DOES support overriding the generated `.desktop` file
// with one named `<launcher-name>.desktop` placed in `--resource-dir`,
// the same mechanism `installer/windows/jpackage/main.wxs` now uses on
// Windows. That migration is NOT done here yet: unlike the Windows side
// (verified by decompiling the actual WixUtilExtension.dll /
// WixUIExtension.dll this project downloads), this machine has no Linux
// JDK to extract jpackage's Linux bundler resources from and confirm the
// exact override filename / any required substitution tokens: jpackage
// ships per-OS bundler code, so a Windows JDK's `jdk.jpackage.jmod`
// contains none of it. Getting this wrong would silently break the
// app-menu entry on every Linux install with no build-time signal. So we
// keep this proven, empirically-verified post-processing step instead of
// guessing at the override contract, exactly like `brandWindowsMsi` used
// to post-process the finished MSI before `main.wxs` replaced it.
//
// Run this instead of `packageDeb` (it depends on it). Idempotent: re-runs
// and an already-correct entry are no-ops.
// ─────────────────────────────────────────────────────────────────────────
tasks.register("fixDebDesktopEntry") {
    dependsOn("packageDeb")
    doLast {
        val osName = System.getProperty("os.name", "").lowercase()
        if (!osName.contains("linux")) {
            logger.warn("fixDebDesktopEntry: not on Linux ($osName), skipping.")
            return@doLast
        }
        val debDir = layout.buildDirectory.dir("compose/binaries/main/deb").get().asFile
        val deb = debDir.listFiles()?.firstOrNull { it.extension == "deb" }
            ?: error("fixDebDesktopEntry: no .deb under $debDir (did :desktop:packageDeb run?)")

        val extractDir = layout.buildDirectory.dir("deb-fix/pkg").get().asFile
        extractDir.deleteRecursively()
        extractDir.mkdirs()
        // Raw-extract control + data tree (preserves file modes).
        exec { commandLine("dpkg-deb", "-R", deb.absolutePath, extractDir.absolutePath) }

        // jpackage ships the entry at /opt/<pkg>/lib/<name>.desktop and
        // registers it at install time via xdg-desktop-menu (postinst), it is
        // NOT under /usr/share/applications inside the .deb. So search the
        // whole DATA tree (everything except the DEBIAN control dir).
        val debianPrefix = "DEBIAN${File.separator}"
        fun isData(f: File) = f.isFile &&
            !extractDir.toPath().relativize(f.toPath()).toString().startsWith(debianPrefix)

        val desktopFiles = extractDir.walkTopDown()
            .filter { isData(it) && it.extension == "desktop" }
            .toList()
        if (desktopFiles.isEmpty()) error("fixDebDesktopEntry: no .desktop file found in the package")

        // 1. Desktop entries: window-class match for the taskbar, and the icon
        //    by theme name instead of the absolute /opt path jpackage writes,
        //    so the icon theme and AppStream can resolve it.
        desktopFiles.forEach { f ->
            var text = f.readText()
            if (!text.contains("StartupWMClass=")) {
                text = text.trimEnd('\n') + "\nStartupWMClass=$linuxWmClass\n"
            }
            text = text.replace(Regex("(?m)^Icon=.*"), "Icon=$linuxIconName")
            f.writeText(text)
            logger.lifecycle("fixDebDesktopEntry: patched ${f.name} (StartupWMClass, Icon=$linuxIconName)")
        }

        // 2. AppStream metainfo + themed icon. The desktop-id is the entry file
        //    name, the one xdg-desktop-menu registers at install time.
        installLinuxMetadata(extractDir, desktopFiles.first().name, "$linuxAppStreamId.metainfo.xml")

        // 3. control: Homepage (shown by apt and the software centers) and a
        //    refreshed Installed-Size now that files were added.
        val control = File(extractDir, "DEBIAN/control")
        var controlText = control.readText()
        if (!controlText.contains("\nHomepage:")) {
            controlText = controlText.replace(Regex("(?m)^Description:"), "Homepage: $nextshHomepage\nDescription:")
        }
        val installedKb = (extractDir.walkTopDown().filter { isData(it) }.sumOf { it.length() } + 1023) / 1024
        controlText = controlText.replace(Regex("(?m)^Installed-Size:.*"), "Installed-Size: $installedKb")
        control.writeText(controlText)

        // 4. md5sums: every data file as "<md5>␠␠<path-without-leading-slash>",
        //    so debsums does not flag the edited or added files.
        val md5File = File(extractDir, "DEBIAN/md5sums")
        if (md5File.exists()) {
            md5File.writeText(
                extractDir.walkTopDown()
                    .filter { isData(it) }
                    .joinToString("") { f ->
                        val rel = extractDir.toPath().relativize(f.toPath()).toString().replace('\\', '/')
                        "${md5(f)}  $rel\n"
                    },
            )
        }

        // Repack in place, same filename so the release process picks it up.
        // --root-owner-group: the raw extraction above ran as the build user,
        // so without it every file of the package would be recorded, then
        // installed under /opt, as owned by that user's uid instead of root.
        exec { commandLine("dpkg-deb", "--root-owner-group", "-b", extractDir.absolutePath, deb.absolutePath) }
        println("✓ .deb patched (desktop entry, AppStream metainfo, icon, Homepage): ${deb.absolutePath}")
    }
}

// ─────────────────────────────────────────────────────────────────────────
// Linux release-artifact collection (Linux only), the analogue of
// `renameWindowsArtifacts`. Copies the .deb and the .AppImage into
// `release-artifacts/` under the canonical names the download table / GitHub
// release use:
//   NextSH_<ver>-1_amd64.deb     (jpackage emits lowercase `nextsh_...`)
//   NextSH-<ver>.AppImage        (packageRealAppImage emits `...-<arch>.AppImage`)
//
// COPY (not move), like the Windows task, so Gradle's incremental machinery
// for packageDeb / packageRealAppImage keeps tracking the originals.
// ─────────────────────────────────────────────────────────────────────────
tasks.register("renameLinuxArtifacts") {
    dependsOn("fixDebDesktopEntry", "packageRealAppImage")
    doLast {
        val osName = System.getProperty("os.name", "").lowercase()
        if (!osName.contains("linux")) {
            logger.warn("renameLinuxArtifacts: not on Linux ($osName), skipping.")
            return@doLast
        }
        val releaseDir = layout.buildDirectory.dir("release-artifacts").get().asFile
            .apply { mkdirs() }

        val deb = layout.buildDirectory.dir("compose/binaries/main/deb").get().asFile
            .listFiles()?.firstOrNull { it.extension == "deb" }
            ?: error("renameLinuxArtifacts: no .deb found (run :desktop:fixDebDesktopEntry)")
        deb.copyTo(File(releaseDir, "NextSH_$desktopVersion-1_amd64.deb"), overwrite = true)

        // The arch-named AppImage produced by packageRealAppImage (e.g.
        // NextSH-<ver>-x86_64.AppImage), match the version-dash prefix so we
        // never pick the canonical NextSH-<ver>.AppImage as our own source.
        val appImage = releaseDir.listFiles()
            ?.firstOrNull { it.name.startsWith("NextSH-$desktopVersion-") && it.name.endsWith(".AppImage") }
            ?: error("renameLinuxArtifacts: no arch AppImage found (run :desktop:packageRealAppImage)")
        appImage.copyTo(File(releaseDir, "NextSH-$desktopVersion.AppImage"), overwrite = true)

        println("✓ Linux artifacts ready in $releaseDir")
    }
}

// SHA-256 of a file as lowercase hex. Used to verify the pinned
// appimagetool download in `packageRealAppImage`.
fun sha256(file: File): String =
    MessageDigest.getInstance("SHA-256").digest(file.readBytes())
        .joinToString("") { "%02x".format(it) }

// MD5 of a file as lowercase hex. Used to regenerate the .deb md5sums
// manifest in `fixDebDesktopEntry`.
fun md5(file: File): String =
    MessageDigest.getInstance("MD5").digest(file.readBytes())
        .joinToString("") { "%02x".format(it) }

// Compose-resources i18n setup. `generateResClass = always` forces the
// plugin to produce the `Res` accessor class regardless of whether code
// already references it (the default `auto` mode skips generation until
// at least one usage exists, which would chicken-and-egg the rollout).
// `publicResClass = true` makes `Res` accessible from this module's code.
compose.resources {
    publicResClass = true
    packageOfResClass = "fr.techtical.nextsh.desktop.generated.resources"
    generateResClass = org.jetbrains.compose.resources.ResourcesExtension.ResourceClassGeneration.Always
}

sqldelight {
    databases {
        create("NextShDatabase") {
            packageName.set("fr.techtical.nextsh.desktop.db")
        }
    }
}

// Skip migration verification: no migration files exist yet, and the SQLite JDBC native lib
// cannot extract to C:\WINDOWS under restricted Gradle worker permissions on this machine.
tasks.matching { it.name.startsWith("verify") && it.name.contains("NextShDatabase") }.configureEach {
    enabled = false
}
